# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
